<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NEXT</name>
   <tag></tag>
   <elementGuidId>75c3d91a-c590-4ac0-8e31-dc25291759b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pull-center.btn.btn-null.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8b94fb8-ddf5-45ae-8bc8-09f9a981f6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e002257e-d1ac-4910-a4f9-c0b004c6b053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-center   btn btn-null btn-success</value>
      <webElementGuid>33af60bc-beeb-4203-86de-7f452a682717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>27d98476-4d74-4eb5-9207-9ac887cc7a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dyno&quot;)/div[@class=&quot;Dynoform---whiteContainer---36RYg ApplicationPanel---container---3K-LQ&quot;]/div[@class=&quot;ApplicationPanel---recipientWrapper---2ZAhb cls_form_wrapper&quot;]/div[@class=&quot;flex-container-fluid&quot;]/div[@class=&quot;DynamicFields---panelWithContainer---VmLml undefined panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[1]/div[@class=&quot;flex-col-xs flex-col-md flex-col-sm flex-col-lg text-center&quot;]/button[@class=&quot;pull-center   btn btn-null btn-success&quot;]</value>
      <webElementGuid>a0631d1a-a820-4134-bb22-1edd157825a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>5292ef96-c95c-4945-b848-f1e5db92a244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dyno']/div/div/div/div/div/div/div[5]/button</value>
      <webElementGuid>d8fbb076-31e9-4bf9-adfc-84227599cab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/following::button[1]</value>
      <webElementGuid>31bf5aad-da8f-4481-a5b9-c4a59e4c3818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self Employed'])[1]/following::button[1]</value>
      <webElementGuid>45e601e1-99f1-4e53-afb7-01273f71eb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT']/parent::*</value>
      <webElementGuid>d821e845-f7f2-49ba-a142-ab575e55db69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>c2fdd3cd-a6c7-449a-824e-22296f54746f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>b58dfe08-9f91-4b7c-9cd8-cefadfd22416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
