<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PIN_Registration---radios---3V54f</name>
   <tag></tag>
   <elementGuidId>7f9c8d9c-5e38-485a-9578-c493d8dfa16f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[3]/div[2]/div/div/div/div[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.Registration---radios---3V54f</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/static/icons/radio_button.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>529ecc37-bbd9-422a-b515-7b62a8319dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Registration---radios---3V54f</value>
      <webElementGuid>af38a3a1-8d63-49eb-83c7-c637f13e2ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/icons/radio_button.svg</value>
      <webElementGuid>4270af73-8067-4116-9b60-882ed3bb7976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;core---childContainer---2GFqG container-fluid&quot;]/div[@class=&quot;Registration---container---PzzMp  container-fluid row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row Registration---reg-wrapper---3xa1A&quot;]/div[@class=&quot;col-lg-7 col-md-7 col-sm-7 col-xs-12 Registration---right-panel---1HFUt&quot;]/div[@class=&quot;loaderParent&quot;]/div[@class=&quot;loaderChildren&quot;]/div[@class=&quot;Registration---right-panel-content---135c3&quot;]/div[@class=&quot;Registration---termsBox---1KLoB&quot;]/div[@class=&quot;row Registration---term-wrapper---2o0oM&quot;]/div[@class=&quot;col-lg-1 col-sm-1 col-md-1 col-xs-1&quot;]/img[@class=&quot;Registration---radios---3V54f&quot;]</value>
      <webElementGuid>bcd7cc86-cf35-4dfb-8953-210ba4a28d9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div[2]/div/div/div/div[4]/div/div/img</value>
      <webElementGuid>569c4ef1-f0d9-4697-8ccd-0cb6bbfbc8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>bfa29b37-188c-4b40-8559-c01fb79e5fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/icons/radio_button.svg']</value>
      <webElementGuid>1dca4674-6ac4-4121-b2ab-06536adabfb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
