<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Join us and become a Maybank2u user tod_06317a</name>
   <tag></tag>
   <elementGuidId>8b488bcb-bbee-496c-951e-4d8c781ec659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mainNav']/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.Navigation---logo---2mLR3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5f6bc72f-b2cf-43f4-aade-7f7ea8638c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Navigation---logo---2mLR3</value>
      <webElementGuid>74eb370e-655a-417f-acc8-7a110df23587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/icons/m2u_logo_white.png</value>
      <webElementGuid>4f8ee348-5dbe-49fc-963b-57ef396dd1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainNav&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;navbar-header&quot;]/a[@class=&quot;navbar-brand page-scroll&quot;]/img[@class=&quot;Navigation---logo---2mLR3&quot;]</value>
      <webElementGuid>505efb52-ec2b-43ac-ae6c-cfb6922da770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mainNav']/div/div/a/img</value>
      <webElementGuid>2349724e-29e8-43f9-b166-5c606120930f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>626adc04-d734-4d4b-aa21-2528b073b756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/icons/m2u_logo_white.png']</value>
      <webElementGuid>75e2698f-7fbf-47cf-8904-ed1f084fc4be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
