<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card  Access Number_Registration---pa_a8d3dc</name>
   <tag></tag>
   <elementGuidId>833941fb-a780-4781-a3e1-d1160de39621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.Registration---pair-input---2_o7S</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4a39c90-fb19-4055-9386-e384a96d5367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a64540a-e57a-44d5-8679-f940ddd918b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>084bac25-e4d8-436d-907c-388c9c4d85f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Registration---pair-input---2_o7S</value>
      <webElementGuid>41d0c53c-5bcd-4766-a244-55d11350dfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex. 1111222233334444</value>
      <webElementGuid>e5a15a47-86f1-4403-97fa-3173872fa2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;core---childContainer---2GFqG container-fluid&quot;]/div[@class=&quot;Registration---container---PzzMp  container-fluid row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row Registration---reg-wrapper---3xa1A&quot;]/div[@class=&quot;col-lg-7 col-md-7 col-sm-7 col-xs-12 Registration---right-panel---1HFUt&quot;]/div[@class=&quot;loaderParent&quot;]/div[@class=&quot;loaderChildren&quot;]/div[@class=&quot;Registration---right-panel-content---135c3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 undefined&quot;]/div[@class=&quot;Registration---input-wrapper---1VaQZ&quot;]/input[@class=&quot;Registration---pair-input---2_o7S&quot;]</value>
      <webElementGuid>ec20af21-4148-46f7-bfaa-e60e91e1eec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>31348390-5065-4efb-aaaa-fd2c62a144ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div[2]/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>8b74a91f-0bee-4be9-b770-7897ffc0a93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f90e85a5-f68f-48c8-a7c8-47f319613b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ex. 1111222233334444']</value>
      <webElementGuid>f526403f-e8df-47f5-8823-372f810aad1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
