<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PIN_Registration---pair-input---2_o7S</name>
   <tag></tag>
   <elementGuidId>370f3810-1040-43b3-bf43-c08b04f750ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5cbfba6-10bc-46b2-9f9d-7a1537cb5f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bea6dece-e0c2-4e7b-914c-2737c67ae975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>3eb9df03-6bb0-4d3f-93d6-5f7fc415e4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Registration---pair-input---2_o7S</value>
      <webElementGuid>5625c997-f82a-4ac5-802a-9ff2353d1527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter 6-digit PIN number</value>
      <webElementGuid>32196835-afd0-47ce-a0bf-d66356c9a4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;core---childContainer---2GFqG container-fluid&quot;]/div[@class=&quot;Registration---container---PzzMp  container-fluid row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row Registration---reg-wrapper---3xa1A&quot;]/div[@class=&quot;col-lg-7 col-md-7 col-sm-7 col-xs-12 Registration---right-panel---1HFUt&quot;]/div[@class=&quot;loaderParent&quot;]/div[@class=&quot;loaderChildren&quot;]/div[@class=&quot;Registration---right-panel-content---135c3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 undefined&quot;]/div[@class=&quot;Registration---input-wrapper---1VaQZ&quot;]/input[@class=&quot;Registration---pair-input---2_o7S&quot;]</value>
      <webElementGuid>f81d3ba2-f9e7-49ed-b6de-202bbd4a9a18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>7ffdbf70-b4bb-4014-90c9-1c98ae575715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div[2]/div/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>f41d8c8f-ea4b-4d6f-8f60-a97d89015d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>e30cc7b7-436e-4f48-8ea6-7c6b75fb0d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter 6-digit PIN number']</value>
      <webElementGuid>668b53f4-7d11-4acc-9581-bb8f91f45c7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
