<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame</name>
   <tag></tag>
   <elementGuidId>c1a484c3-9a3d-4c81-bbfe-2abb0297de91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/frameset[1]/frame[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>ef672782-d9e7-4f0c-9c77-b415c635f28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../common/mbbPortalAccess.do?action=Login&amp;BrowserCompatible=&amp;screen=&amp;accntType=&amp;navi=&amp;BV_SessionID=@@@@1440818443.1676540074@@@@&amp;BV_EngineID=ccdfadikjhmheeecefecfledfmodflh.0</value>
      <webElementGuid>1d1fc084-24ab-4e00-b8ab-c05eb5eacde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>a9a119fd-f24e-4f5d-976e-34471707c60d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>d5f07880-0384-4263-82bd-860645a3f5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = '../common/mbbPortalAccess.do?action=Login&amp;BrowserCompatible=&amp;screen=&amp;accntType=&amp;navi=&amp;BV_SessionID=@@@@1440818443.1676540074@@@@&amp;BV_EngineID=ccdfadikjhmheeecefecfledfmodflh.0']</value>
      <webElementGuid>cb3f6216-95bc-4dc1-8634-53be8edd1dda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
