<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Discover</name>
   <tag></tag>
   <elementGuidId>6d5f157b-bf80-4e50-80ce-d859439d519c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='discover']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#discover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ef20af1-7ff0-4212-806b-6ceb00387893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>discover</value>
      <webElementGuid>926a822e-b357-4c29-9ec4-3befea4b9aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discover</value>
      <webElementGuid>d53d6aef-142b-4b6b-8c1f-1fa46b21323b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eada9966-15bf-4cfc-a7fb-0d5236e19ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:var url=$('.select-account-2 option:selected').val(); console.log('url:'+url); window.location.href=url</value>
      <webElementGuid>6f5fc010-e118-45af-8d22-851cf6f62143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Discover</value>
      <webElementGuid>fe634295-854c-4799-a0a8-c3c3bdc815c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c0a2547b-a82b-4d39-a341-50159bc03f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Discover</value>
      <webElementGuid>9f69f770-7828-4f1b-82c5-aecc432eebd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>														Discover</value>
      <webElementGuid>157ca1de-34ba-4233-9b5c-f030093c5d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discover&quot;)</value>
      <webElementGuid>3aaa79b7-4642-4c9b-9738-07a5ef06dbd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='discover']</value>
      <webElementGuid>1b82189c-2ba1-4d44-bada-c499fbeda9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iw_comp1505277382971']/section/section/div/div/div/button</value>
      <webElementGuid>92bf172e-20cb-4e66-9bcb-727591137b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Loan'])[1]/following::button[1]</value>
      <webElementGuid>6de9f9a5-6e72-4ab4-9f36-9853e1161528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am interested in'])[1]/following::button[1]</value>
      <webElementGuid>f58b26a7-fc09-4e65-8a2a-0ac9a5c36dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>9db2f011-1123-4e8b-be86-f9ba12a11d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get A Loan'])[1]/preceding::button[1]</value>
      <webElementGuid>1e39d287-a2a4-4e9c-b7dd-c1268b169982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Discover']/parent::*</value>
      <webElementGuid>343d7ed5-0db2-4ed0-85ec-2e397d963b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>54aa03db-d3ca-42a0-829f-161b5da38a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'discover' and @id = 'discover' and @type = 'button' and @title = 'Discover' and (text() = '														Discover' or . = '														Discover')]</value>
      <webElementGuid>f11eb601-7fec-4bf2-9cb7-b45d5e7749b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
