<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RESUME APPLICATION</name>
   <tag></tag>
   <elementGuidId>a5ebee56-3eac-44c2-b62e-b4fabdd9be83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-resume']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-resume&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9e67575-81c5-43d2-be8a-f235a9ba2e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>860ff819-de99-4ca3-a7ae-9aa6c7cc9a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-resume</value>
      <webElementGuid>0eb086ba-d30d-4fa5-9b03-1c482ce5e6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white</value>
      <webElementGuid>c23c7731-a4ea-4e06-9261-fb133190d614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location.href='https://www.maybank2u.com.my/home/m2u/common/page/apply/cardSTP.do?productType=cardSTP&amp;type=resume'</value>
      <webElementGuid>ff2bdbe1-de64-42e4-8472-76338a91c3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>RESUME APPLICATION</value>
      <webElementGuid>c4eee16c-83d8-48e5-ac43-fffd467fb25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RESUME APPLICATION</value>
      <webElementGuid>164bafea-e165-4b30-8073-016bf5a195d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iw_comp1601456083848&quot;)/div[@class=&quot;container&quot;]/section[@class=&quot;inner-container&quot;]/section[@class=&quot;secondary-header header-compare on-top&quot;]/div[@class=&quot;clear-mobile&quot;]/button[@class=&quot;btn btn-white&quot;]</value>
      <webElementGuid>f79c32dd-c865-47d8-8ec2-9d7528e6d652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-resume']</value>
      <webElementGuid>d6a09097-a49e-4a75-9a37-69ba21bb195e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iw_comp1601456083848']/div/section/section/div[2]/button</value>
      <webElementGuid>b1cdfeca-915e-47bd-8e33-a32507916be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Features'])[1]/following::button[1]</value>
      <webElementGuid>b1e556b7-6798-4121-a214-d1b9948cb0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[2]</value>
      <webElementGuid>6cc98317-37e9-475e-978e-18f2d18503a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPARE'])[1]/preceding::button[1]</value>
      <webElementGuid>1af634cc-9726-47f7-a1f5-32ecb6468183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLY'])[1]/preceding::button[2]</value>
      <webElementGuid>771da16c-eda8-4d83-a909-f1073756ecef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RESUME APPLICATION']/parent::*</value>
      <webElementGuid>d49f9089-0aec-4904-9862-0a5ba6b26809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>cf22c7f0-0b47-41c4-9d37-7069b03881d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'btn-resume' and (text() = 'RESUME APPLICATION' or . = 'RESUME APPLICATION')]</value>
      <webElementGuid>08cf48c8-b0c0-46d0-90cd-119e70a375cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
