<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RESUME</name>
   <tag></tag>
   <elementGuidId>3480aa14-52b2-4448-8a4f-93d6d4e1cd2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pull-right.btn.btn-null.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a0defe8-3a8a-4978-959f-30b5aca782f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40a60e01-03de-4c15-9286-6669b048a107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right   btn btn-null btn-success</value>
      <webElementGuid>d5b266c6-3521-4f98-a53b-a5ea65026a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RESUME</value>
      <webElementGuid>590c16d8-1ebe-497a-ac0e-ab66a59c880b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dyno&quot;)/div[@class=&quot;Dynoform---whiteContainer---36RYg ApplicationPanel---container---3K-LQ&quot;]/div[@class=&quot;ApplicationPanel---recipientWrapper---2ZAhb cls_form_wrapper&quot;]/div[@class=&quot;flex-container-fluid&quot;]/div[@class=&quot;DynamicFields---dynoWhiteContainer---1qQmr&quot;]/div[@class=&quot;DynamicFields---stretch---2PB6O ApplicationPanel---inputPair---3wAZs  flex-row&quot;]/div[@class=&quot;flex-col-xs flex-col-md flex-col-sm flex-col-lg&quot;]/button[@class=&quot;pull-right   btn btn-null btn-success&quot;]</value>
      <webElementGuid>0a82b6c9-2da3-4ef1-8ee7-d2a7e90cc407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>1468c376-8475-46b4-8fa3-3c6743315870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dyno']/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>baa76320-329f-4a17-963d-54550e0035cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IC No.'])[1]/following::button[1]</value>
      <webElementGuid>2ef1f090-a043-43d3-ab7b-e313b08fe121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESUME APPLICATION'])[1]/following::button[1]</value>
      <webElementGuid>7c0caa58-af1b-4c02-b8af-ebb42e145936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RESUME']/parent::*</value>
      <webElementGuid>22bfb2af-07c0-40c3-b3e6-e425c9d810d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>82d73ec8-2561-4c0f-863b-4b9c8ceb5b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'RESUME' or . = 'RESUME')]</value>
      <webElementGuid>61a560a8-ef8c-470e-9f17-ed3bc91f43b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
