<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ACCOUNTS</name>
   <tag></tag>
   <elementGuidId>69727196-9ea7-4867-af90-c2abdb19cc99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToDetails']/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Navigation---typeName---1-l6x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0739ad9c-d516-45c4-83f9-e9a4b655f638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Navigation---typeName---1-l6x</value>
      <webElementGuid>9fed35c4-c0ab-4956-a604-2a9673b01f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCOUNTS</value>
      <webElementGuid>11d16587-b111-4452-97e3-67b38bc4f7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToDetails&quot;)/div[@class=&quot;details---container---3jYDY&quot;]/div[@class=&quot;loaderParent&quot;]/div[@class=&quot;loaderChildren&quot;]/div[@class=&quot;details---topSection---3Xqqm details---topFixed---3GY6l&quot;]/div[@class=&quot;details---navigation---1Gb6o&quot;]/div[@class=&quot;container-fluid Navigation---container---1wp-0 Navigation---noAccumulatedBal---3GVIF&quot;]/div[@class=&quot;Navigation---navigationContent---2Emt-&quot;]/div[@class=&quot;row mobile&quot;]/div[@class=&quot;col-sm-12 col-md-10 hidden-xs Navigation---menuHolder---tJeh7&quot;]/div[@class=&quot;Navigation---selected---2tF_N hidden-xs Navigation---nav-tabs---3ZMpw&quot;]/div[1]/div[@class=&quot;Navigation---desktopcontainer---1hrGV&quot;]/div[@class=&quot;Navigation---typeName---1-l6x&quot;]</value>
      <webElementGuid>0616263a-c94c-4584-a94e-199994f7094a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToDetails']/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>579c08fb-68a7-46f9-aed3-53f7377ac992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT US'])[1]/following::div[15]</value>
      <webElementGuid>7bc677d8-0b45-4e24-9451-cfbc9eeb6bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARDS'])[1]/preceding::div[1]</value>
      <webElementGuid>43ef3e27-f564-49bc-a66e-9c66a0080f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEALTH'])[1]/preceding::div[5]</value>
      <webElementGuid>becc363d-2169-4700-82ba-7612cbb95b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCOUNTS']/parent::*</value>
      <webElementGuid>ce035abf-f527-4b0f-aceb-c5c08fc538d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>f85d45fe-76b0-48d0-bb2d-057f8f80d2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ACCOUNTS' or . = 'ACCOUNTS')]</value>
      <webElementGuid>ea8f0fd4-ebf1-4525-b79e-e15db62089f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
