<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_INDAH WATER CAP SQUARE_img-responsive h_d77821</name>
   <tag></tag>
   <elementGuidId>7afc7e5f-1878-4fdb-95d2-cc989c1646d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive.hidden-xs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9b6597f2-1073-47cd-a90e-67ff2eb19076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive hidden-xs</value>
      <webElementGuid>d3071d4c-3924-4fea-8b7a-9770930d1b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/iwov-resources/images/upload/popup-web.jpg</value>
      <webElementGuid>1b0efb7c-12c5-4d7f-ab11-b246b0ecaa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[4]/div[@class=&quot;fade PromotionalModal---container---1oaNH AnnouncementModal---announcementModal---3YygH in modal&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;promotional-body modal-body&quot;]/a[1]/img[@class=&quot;img-responsive hidden-xs&quot;]</value>
      <webElementGuid>6aee6008-b045-465c-ab2b-539ae5aaed8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>3b48e471-fc60-4c35-955d-ed949e43c2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/iwov-resources/images/upload/popup-web.jpg']</value>
      <webElementGuid>ceed2acf-4db8-42e7-8624-24e73d6cb085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
