<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Successful</name>
   <tag></tag>
   <elementGuidId>961b0e4c-d5ec-4227-bfe5-17e784555a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p[@id='statusSuccess'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status > #statusSuccess</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>102caf1d-0a34-48ea-bd44-8e1efec7c9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LogoutContent---success---2reX_</value>
      <webElementGuid>9b0feda2-2bde-4e3c-9fac-2384846670e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statusSuccess</value>
      <webElementGuid>e6f2392c-fcf5-4e42-a255-e42b78beec8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successful</value>
      <webElementGuid>ae8c4bb8-fa01-4f58-8fed-5ef5b3d46274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status&quot;)/p[@id=&quot;statusSuccess&quot;]</value>
      <webElementGuid>c290a027-1c6b-49d9-9fee-97262735cdf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//p[@id='statusSuccess'])[2]</value>
      <webElementGuid>4dc8216e-bb69-4e73-9774-a0366288bfc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='status']/p</value>
      <webElementGuid>2508b4c5-9993-428a-a669-7bd121e2f68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 0.10'])[2]/following::p[1]</value>
      <webElementGuid>2d8036e0-493c-44ee-bb01-72a607315265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOHAMMAD MOSAJ GOHAR 164017298921'])[2]/following::p[1]</value>
      <webElementGuid>9cf894e3-6270-4b37-a816-855be9a2c62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/preceding::p[2]</value>
      <webElementGuid>7407d46f-7949-4b80-88ab-ec7202f75c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have logged out!'])[2]/preceding::p[2]</value>
      <webElementGuid>abc1b8f0-e1b8-4011-947c-149b6c9b64d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>bb093027-48b4-43a9-9391-8b2adc17ca87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'statusSuccess' and (text() = 'Successful' or . = 'Successful')]</value>
      <webElementGuid>e25ae4f0-35a7-4403-8868-434f6feb450b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
