<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Discover</name>
   <tag></tag>
   <elementGuidId>2bc314be-43de-4f8e-ac99-d425585a02cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='discover']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#discover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f8cb9c7-12a5-4e42-8ae7-38e18f17e0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dedadea2-85b6-4fc2-a1d5-efe469d47c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>discover</value>
      <webElementGuid>17f0855b-150d-4a44-8d76-fd4843a52c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discover</value>
      <webElementGuid>6b614546-71a0-4942-bb52-a24b5ccf9786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>ca29daf7-b385-4003-b180-c2db3378d05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var selected=$('.select-card option:selected').data('modal-template'); if (selected==null || selected.length == 0) { window.location.href=$('#card-form select[name=card-select]').val();}</value>
      <webElementGuid>769d4cc6-e592-4fe9-8b48-bb993db22b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>DISCOVER</value>
      <webElementGuid>624e3e0b-6679-4613-b4eb-8cf781634664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>						Discover					</value>
      <webElementGuid>bfe888a2-86c1-4d5d-8112-c95d1dfd32cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-form&quot;)/div[@class=&quot;group-account&quot;]/button[@id=&quot;discover&quot;]</value>
      <webElementGuid>75ba1115-ca4b-4145-8e15-0d03ac7fcdf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='discover']</value>
      <webElementGuid>5852ec91-6510-4723-a19e-69d598e6bdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='card-form']/div/button</value>
      <webElementGuid>74e28cb3-532b-4d8f-b176-aec1b0b844f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Cards'])[1]/following::button[1]</value>
      <webElementGuid>b8825ed2-a5fb-4fa6-b171-86a139091bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am looking for'])[1]/following::button[1]</value>
      <webElementGuid>61634ca7-2e15-48a8-bf05-e0043d2342f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find The Right Card'])[1]/preceding::button[1]</value>
      <webElementGuid>e830127d-d324-4757-8036-4ecd0b7eebf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let’s find the right credit card for you.'])[1]/preceding::button[1]</value>
      <webElementGuid>e41c0794-94f7-4846-9f72-6779428db6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Discover']/parent::*</value>
      <webElementGuid>0c3cc1c2-d54b-499a-8a0a-997f6bec2641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>53c5e153-1bbf-4b68-a662-f4936936c0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'discover' and @id = 'discover' and (text() = '						Discover					' or . = '						Discover					')]</value>
      <webElementGuid>60ac6947-7139-4c4a-b2d2-a2d472b3d839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
