<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Find The Right Card</name>
   <tag></tag>
   <elementGuidId>4c722e47-0ead-4b33-afef-cfa5d379b3c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='discover'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.find-right-card > #discover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1eb99080-2897-4a6c-a808-fabe41a304ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>discover</value>
      <webElementGuid>c14c600d-c873-4bf9-8890-26020226f987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discover</value>
      <webElementGuid>2d0a4fcf-1a1f-445a-80bf-1cab4fcfb54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>353642cb-57b1-4dfe-a497-cd1740e07b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: var url=$('select[name=card-select]').val(); var segments=''; var minimum=$('#amount').val(); minimum = minimum * 12; $( '#segments input:checked').each(function(){ segments= segments + this.value + ', ' ; }); var segmenting=segments.replace(/(^[,\s]+)|([,\s]+$)/g, ''); var param= $('#paramval').val(); console.log('URL:'+url+'q='+segmenting+'&amp;mt='+minimum); window.location.href=url+'q='+segmenting+'&amp;nt='+minimum;</value>
      <webElementGuid>2f30128d-fdd7-423d-9070-073bc4cfb9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Find The Right Card</value>
      <webElementGuid>2b349d0b-2a01-4342-b445-80865fef1fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>9d72b775-9f9b-40a1-81f5-37fa6db3cad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Find The Right Card</value>
      <webElementGuid>31c3ba4d-4669-466e-a131-b4ff45d3ed3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>						Find The Right Card											</value>
      <webElementGuid>00501b83-f437-4392-9263-123455d49f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc-chose&quot;)/div[@class=&quot;interesting&quot;]/div[@class=&quot;find-right-card&quot;]/button[@id=&quot;discover&quot;]</value>
      <webElementGuid>75c9d180-74b4-4fbf-82a8-5ba92e58628f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='discover'])[2]</value>
      <webElementGuid>387f78de-e1cb-4c9f-8f8e-bc1e6511cf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cc-chose']/div[2]/div/button</value>
      <webElementGuid>d8f035ec-3ff5-422c-a623-decbf01aca70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLINE SHOPPING'])[1]/following::button[1]</value>
      <webElementGuid>512753b3-78e8-4a1f-bced-fccb87145b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISLAMIC'])[1]/following::button[1]</value>
      <webElementGuid>d42dbfcb-b4fc-46a9-b7ae-3a0b84a03001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>228b655f-aaf7-44dc-a550-a6288f26c6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maybank Cards'])[1]/preceding::button[1]</value>
      <webElementGuid>2f2b9740-0e86-47b7-b23e-47f2aab63963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>f0f083dc-21a8-428c-a3ba-a141bd937ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'discover' and @id = 'discover' and @type = 'button' and @title = 'Find The Right Card' and (text() = '						Find The Right Card											' or . = '						Find The Right Card											')]</value>
      <webElementGuid>ee67aa8e-6917-4b6a-a4c8-6349b10de184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
